dist: xenial
os: linux
language: node_js
node_js:
  - 12

services:
  - docker
  - postgresql

addons:
  postgresql: "13.0"
  apt:
    packages:
      - postgresql-13-postgis-3

before_script:
  - . features/.env
  - export DB_PASSWORD='' DB_HOSTNAME='localhost'
  - psql -c "CREATE EXTENSION IF NOT EXISTS postgis" -U postgres
  - psql -c "CREATE DATABASE $DB_NAME;" -U postgres

script:
  - npm run test:coverage
  - codecov -f coverage/*.json

deploy:
  provider: script
  script: bash docker/heroku_push.sh
  cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = develop
