global:
  scrape_interval:     15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'apps'
    scrape_interval: 5s
    metrics_path: '/v1/metricas'
    static_configs:
      - targets: ['app:3000']
        labels:
          group: 'core'
      - targets: ['payments-app:4000']
        labels:
          group: 'payments'
      - targets: ['users-app:5000']
        labels:
          group: 'users'
