apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookbnb-core
  labels:
    app: bookbnb-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookbnb-core
  template:
    metadata:
      labels:
        app: bookbnb-core
    spec:
      containers:
      - name: core
        image: ghcr.io/bookbnb/core
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: core-secret
          - configMapRef:
              name: core-config
