apiVersion: v1
kind: Service
metadata:
  name: bookbnb-core-service
  labels:
    run: bookbnb-core-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: bookbnb-core
