name: CD to heroku
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Start services
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: sleep 5; docker-compose logs
      - name: Run test suite
        run: |
          docker-compose exec -T app npm install
          docker-compose exec -T app npm run test:coverage

