name: CD to heroku
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true # Ignore the failure of a step and avoid terminating the job.
      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-dependencies
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker services
        run: docker-compose build
      - name: Start services
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Run test suite
        run: |
          docker-compose exec -T app npm install
          docker-compose exec -T app npm run test:coverage
      - name: Send coverage report
        run: docker-compose exec -T app codecov -f coverage/*.json
