name: CD to heroku
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Start services
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run test suite
        run: docker-compose exec app npm run test:coverage

